---
- name: install vsftpd
  hosts: ansible3
  tasks:
  - name: install vsftpd
    yum:
      name: vsftpd
      state: installed
  - name: start and enable vsftpd
    service:
      name: vsftpd
      state: started
      enabled: yes
  - name: Allow FTP service in Firewall
    firewalld:
      service: ftp
      permanent: yes
      state: enabled
      immediate: true

- name: configure vsftpd using a template
  hosts: ansible3
  vars:
    anonymous_enable: yes
    local_enable: yes
    write_enable: yes
    anon_upload_enable: yes
  tasks:
  - name: use template to copy FTP config
    template:
      src: lab-vsftpd.j2
      dest: /etc/vsftpd/vsftpd.conf

- name: configure vsftpd permissions and selinux
  hosts: ansible3
  vars:
    anon_root: /var/ftp/pub
  tasks:
  - name: install required selinux tools
    yum:
      name: policycoreutils-python-utils
      state: present
  - name: set permissions
    file:
      path: "{{ anon_root }}"
      mode: 0777
  - name: set selinux boolean
    seboolean:
      name: ftpd_anon_write
      state: yes
      persistent: yes
  - name: manage selinux settings
    sefcontext:
      target: "{{anon_root}}"
      setype: public_content_rw_t
      state: present
    notify:
      - run restorecon
  handlers:
    - name: run restorecon
      command: restorecon -vR {{anon_root}}
