---
- name: undo lab 7
  hosts: ansible3
  tasks:
  - name: stop firewall
    service:
      name: firewalld
      state: stopped
    become: yes
  - name: stop vsftpd
    service:
      name: vsftpd
      state: stopped
    become: yes
  - name: Uninstall firewall
    yum:
      name: firewalld
      state: absent
    become: yes
  - name: Uninstall vsftpd
    yum:
      name: vsftpd
      state: absent
    become: yes
