---
- name: show arrays
  hosts: ansible1
  vars_files:
    - vars/users
  tasks:
    - name: print array values
      debug:
        msg: "Users {{ users.linda.username }} has homedirectory {{ users.linda.homedir }} and shell {{ users.linda.shell }}"
