---
- name: failed_when demo
  hosts: all
  tasks:
    - name: run a sceipt
      command: echo hello world
      ignore_errors: yes
      register: command_result
      failed_when: "'world' in command_result.ctd_out"
    - name: see if we get here
      debug:
        msg: hello