---
- name: install custom facts
  hosts: web
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: localfacts.fact
  tasks:
    - name: create fact directory
      file:
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"
    - name: install new facts
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"
